# Generated by Django 5.2.16 on 2026-07-24 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('course_materials', 'Course Materials'), ('electronics', 'Electronics'), ('tools', 'Tools'), ('kitchen_items', 'Kitchen Items'), ('clothing', 'Clothing'), ('recreation', 'Recreation'), ('other', 'Other')], max_length=32)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair')], max_length=20)),
                ('pickup_area', models.CharField(choices=[('north_residential', 'North Residential Village'), ('south_residential', 'South Residential Village'), ('case_quad', 'Case Quad'), ('mather_quad', 'Mather Quad'), ('health_campus', 'Health Education Campus'), ('uptown', 'Uptown'), ('little_italy', 'Little Italy'), ('coventry', 'Coventry'), ('other_nearby', 'Other Nearby Area')], max_length=32)),
                ('available_from', models.DateField()),
                ('available_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
